<?php

require_once DIR . '/fpdf/fpdf.php';

function generateParcelPDF($trackingNumber, $sender, $receiver, $status, $location)
{
    $pdf = new FPDF();

    $pdf->AddPage();

    $pdf->SetFont('Arial', 'B', 16);
    $pdf->Cell(0, 10, 'Parcel Tracking Report', 0, 1, 'C');

    $pdf->Ln(10);

    $pdf->SetFont('Arial', '', 12);

    $pdf->Cell(50, 10, 'Tracking Number:');
    $pdf->Cell(0, 10, $trackingNumber, 0, 1);

    $pdf->Cell(50, 10, 'Sender:');
    $pdf->Cell(0, 10, $sender, 0, 1);

    $pdf->Cell(50, 10, 'Receiver:');
    $pdf->Cell(0, 10, $receiver, 0, 1);

    $pdf->Cell(50, 10, 'Status:');
    $pdf->Cell(0, 10, $status, 0, 1);

    $pdf->Cell(50, 10, 'Current Location:');
    $pdf->Cell(0, 10, $location, 0, 1);

    $pdf->Ln(10);

    $pdf->Cell(0, 10, 'Generated by Parcel Tracking System', 0, 1, 'C');

    $pdf->Output();
}

?>